---
framework: jest
preRun:
     command:
        - npm ci
        - npm run build
preMerge:
  pattern:
    - "test/test.ts"
postMerge:
  pattern: 
    - "test/test.ts"
postRun:
     command:
        - npm --version
version: 1.0
